version: '3'
services:
  strapi:
    build:
      context: ./docker/cms
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${STRAPI_PORT}:1337"
    networks:
      - lapp
    volumes:
      - ./cms:/cms
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    command: sh -c "if [ \"$NODE_ENV\" = 'production' ]; then npm run start; else npm install && npm run develop; fi"
    tty: true

  nuxt:
    build:
      context: ./docker/ui
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${NUXT_PORT}:3000"
    networks:
      - lapp
    volumes:
      - ./ui:/ui
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    command: sh -c "if [ \"$NODE_ENV\" = 'production' ]; then npm run build && npm run start; else npm install && npm run dev; fi"
    tty: true

networks:
  lapp:
    driver: bridge
