version: '3'
services:
  strapi:
    build:
      context: ./docker/cms
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    networks:
      - lapp
    volumes:
      - ./cms:/cms
    command: sh -c "npm install && npm run develop"
    tty: true

  nuxt:
    build:
      context: ./docker/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - lapp
    volumes:
      - ./ui:/ui
    command: sh -c "npm install && npm run dev"
    tty: true
networks:
  lapp:
    driver: bridge